name: The Best Worst Car Reviews
favicon: null
layout_spectrum: 0.8208950485568494
typography_spectrum: 0.4053218134213239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6268814257346094
  lightness: 0.03334180265665054
  saturation: 0.4049140876159072
  rhythmicContrast: 0.8790437725838274
purpose: []
